# Generated by Django 5.2.8 on 2025-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
