# Generated by Django 5.2.8 on 2025-12-02 20:18

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=10)),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 12, 2, 20, 18, 41, 743735, tzinfo=datetime.timezone.utc))),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('slot_number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
