# Generated by Django 5.2.8 on 2025-11-30 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=10)),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 11, 30, 17, 44, 15, 88389, tzinfo=datetime.timezone.utc))),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('slot_number', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
