# Generated by Django 5.2.8 on 2025-11-30 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='reserved_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
