# Generated by Django 5.2.8 on 2025-11-30 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 18, 24, 41, 214413, tzinfo=datetime.timezone.utc)),
        ),
    ]
