# Generated by Django 5.2.8 on 2025-12-03 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 3, 17, 16, 37, 919112, tzinfo=datetime.timezone.utc)),
        ),
    ]
