# Generated by Django 5.2.8 on 2025-12-01 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 20, 12, 10, 726651, tzinfo=datetime.timezone.utc)),
        ),
    ]
